set(LIBRARY_ROOT "${DEPENDENCIES_FOLDER}/boost_1_72_0")

set(BOOST_FOUND TRUE)
set(BOOST_INCLUDE_DIRS "${LIBRARY_ROOT}")

mark_as_advanced(FORCE BOOST_FOUND)
mark_as_advanced(FORCE BOOST_INCLUDE_DIRS)
