set(LIBRARY_ROOT "${LIBRARY_REPOSITORY_ROOT}/capstone")

set(CAPSTONE_FOUND TRUE)
set(CAPSTONE_INCLUDE_DIRS "${LIBRARY_ROOT}/include")

if(DEFINED WIN32)
  set(LIBRARY_PREFIX "")
  set(LIBRARY_EXTENSION "lib")
else()
  set(LIBRARY_PREFIX "lib")
  set(LIBRARY_EXTENSION "a")
endif()

set(CAPSTONE_LIBRARIES
  ${LIBRARY_ROOT}/${LIBRARY_PREFIX}capstone_static.${LIBRARY_EXTENSION}  
)

mark_as_advanced(FORCE CAPSTONE_FOUND)
mark_as_advanced(FORCE CAPSTONE_INCLUDE_DIRS)
mark_as_advanced(FORCE CAPSTONE_LIBRARIES)
